### ISSUE TITLE
 Property 'share' does not exist on type 'Observable<string>'.

### ISSUE THREAD

**Issue by rahulrsingh09** [ohjames/rxjs-websockets#17] opened 2017-10-04 17:04 UTC
When i try to implement the dummy example i get this error  Property 'share' does not exist on type 'Observable<string>'.

**Comment by axleonard** [comment] 2017-10-04 22:18
Are you using the latest version of RxJS? This is working for me with 5.4.3.

**Comment by ohjames** [comment] 2017-10-05 11:57
You have not imported rxjs correctly. Please read their documentation.

**Comment by ohjames** [comment] 2017-10-05 11:58
Also a duplicate of #16

**Closed by ohjames** 2017-10-05 11:57 UTC

**Comment by ohjames** [comment] 2017-10-05 12:01
@axleonard Thanks, I've added this import to the example in the readme.
